openapi: 3.0.0
info:
  title: 'HiReach API'
  description: "This is a documentation HiReach API server."
  contact:
    email: support@hireach.com
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.1.1
servers:
  -
    url: 'https://hireach.test/dapi'
    description: 'HiReach API Sandbox'
  -
    url: 'https://hireach.test/api'
    description: 'HiReach API Production'
paths:
  /one-way:
    post:
      tags:
        - one way
      summary: 'Sending text to many channel'
      operationId: postOneWayResource
      requestBody:
        $ref: '#/components/requestBodies/OneWayArray'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - bearerAuth: []
    get:
      tags:
        - one way
      summary: 'Get all one way resource'
      operationId: getOneWayResource
      parameters:
        -
          name: provider
          in: query
          required: true
          schema:
            type: string
            enum: [provider-1, provider-2]
        -
          name: page
          in: query
          required: true
          default: 0
          schema:
            type: integer
        -
          name: pageSize
          in: query
          required: true
          default: 10
          schema:
            type: integer
        -
          name: order
          in: query
          required: false
          schema:
            type: string
            enum: [id, newest, oldnest]
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleSms'
            application/xml:
              schema:
                $ref: '#/components/schemas/SingleSms'
        '400':
          description: 'Invalid supplied'
        '404':
          description: 'Record not found'
      security:
        - bearerAuth: []
  /two-way:
    post:
      tags:
        - two way
      summary: 'Send sms to list of Recipients mobile number with given input array'
      operationId: sendBulkSms
      requestBody:
        $ref: '#/components/requestBodies/SmsArray'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - bearerAuth: []
  /chat:
    post:
      tags:
        - chat
      summary: 'Send a message with form data'
      operationId: sendChat
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                team:
                  description: 'Slug Name Team'
                  required: true
                  type: string
                phone:
                  description: 'From no phone'
                  required: true
                  type: string
                  format: msisdn
                text:
                  description: 'Reply of the chat'
                  required: true
                  type: string
              type: object
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '422':
          description: 'Invalid input'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputChat'
      security:
        - bearerAuth: []
  '/chat/{phone_number}':
    get:
      tags:
        - chat
      summary: 'Returns chat message by number'
      description: 'Returns a chat conversation message per phone number'
      operationId: getChat
      parameters:
        -
          name: phone_number
          in: path
          required: true
          schema:
            type: string
            format: msisdn
      responses:
        '200':
          description: 'successful operation'
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Chat'
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '400':
          description: 'Invalid phone number provided'
        '404':
          description: 'User not found'
      security:
        - bearerAuth: []
  /sms:
    get:
      tags:
        - sms
      summary: 'Return all sms record'
      operationId: getSms
      parameters:
        - name: start_date
          in: query
          type: string
          format: date
          description: >
            The start date for the report. Must be used together with `end_date`.
          example: '2022-01-20'
        - name: end_date
          in: query
          type: string
          format: date
          description: >
            The end date for the report. Must be used together with `start_date`.
          example: '2022-01-20'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleSms'
        '400':
          description: 'Invalid supplied'
        '404':
          description: 'Record not found'
      security:
        - bearerAuth: []
    post:
      tags:
        - sms
      summary: 'Send sms to Recipient mobile number'
      operationId: sendSms
      requestBody:
        description: 'Send sms object'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSms'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - bearerAuth: []
  '/sms/{phone_number}':
    get:
      tags:
        - sms
      summary: 'Return all sms record'
      operationId: getSmsByPhone
      parameters:
        -
          name: phone_number
          in: path
          required: true
          schema:
            type: string
            format: msisdn
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleSms'
            application/xml:
              schema:
                $ref: '#/components/schemas/SingleSms'
        '400':
          description: 'Invalid supplied'
        '404':
          description: 'Record not found'
      security:
        - bearerAuth: []
  /sms/bulk:
    post:
      tags:
        - sms
      summary: 'Send sms to list of Recipients mobile number with given input array'
      operationId: sendBulkSms
      requestBody:
        $ref: '#/components/requestBodies/SmsArray'
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - bearerAuth: []

components:
  schemas:
    ApiResponse:
      title: 'Api response'
      description: 'Api response'
      properties:
        message:
          title: Message
          description: Message
          type: string
          example: "Successful"
        code:
          title: Code
          description: Code
          type: integer
          format: int32
          example: 200
        response:
          title: Response
          description: Response
          type: array
          items:
            type: string
      type: object
    SingleSms:
      title: 'Single SMS Response'
      description: 'Single SMS model'
      required:
        - type
        - to
        - from
        - text
        - servid
      properties:
        id:
          title: ID
          description: ID
          type: integer
          format: int64
        type:
          title: 'Type'
          description: 'Character type for text'
          type: integer
          format: int64
        title:
          title: 'Title'
          description: 'Broadcast Title'
          type: string
        servid:
          title: 'ServId'
          description: 'ServID'
          type: string
        text:
          title: 'Text'
          description: 'Message Content'
          type: string
        to:
          title: 'To'
          description: 'The recipient’s mobile number must have the country code (without the “+” sign).'
          type: string
        status:
          title: 'Status'
          description: 'Broadcast status'
          type: string
        date:
          title: 'Date'
          description: 'Broadcast date'
          type: string
          format: date-time
        otp:
          title: 'OTP'
          description: 'SMS Type OTP or NON OTP'
          type: boolean
      type: object
      xml:
        name: SingleSms
    BulkSms:
      title: 'Bulk SMS model'
      description: 'Bulk SMS model'
      required:
        - type
        - to
        - from
        - text
        - servid
      properties:
        type:
          title: 'Type'
          description: 'Character type for text'
          type: integer
          format: int64
        title:
          title: 'Title'
          description: 'Broadcast Title'
          type: string
        servid:
          title: 'ServId'
          description: 'ServID'
          type: string
        text:
          title: 'Text'
          description: 'Message Content'
          type: string
        from:
          title: 'From'
          description: 'Sender Name'
          type: string
        to:
          title: 'To'
          description: 'The recipient`s mobile number must have the country code (without the “+” sign).'
          type: string
          format: msisdn
        otp:
          title: 'OTP'
          description: 'SMS Type OTP or NON OTP'
          type: boolean
      type: object
      xml:
        name: BulkSms
    OneWayRequest:
      title: 'One Way Model'
      description: 'One Way Model'
      required:
        - channel
        - type
        - to
        - text
        - title
      properties:
        channel:
          title: 'channel'
          description: 'Channel resource to send content: email, wa, sms_otp_sid, sms_notp_sid, sms, talkbot'
          type: string
          default: 'email'
        type:
          title: 'type'
          description: 'Type for content. Default is 0 for text.'
          type: integer
          format: int64
        title:
          title: 'title'
          description: 'Broadcast Title'
          type: string
          default: 'New Product Launch'
        text:
          title: 'text'
          description: 'Message Content'
          type: string
          default: 'Hi, [Name], your canvas design account has been updated with the following features in March. Find out more on our website!'
        templateid:
          title: 'templateid'
          description: ''
          type: integer
          default: 1
        to:
          title: 'to'
          description: 'The recipient`s mobile number must have the country code (without the “+” sign). Ex: 6281223344556'
          type: string
          format: msisdn
        from:
          title: 'from'
          description: 'Sender Name if using SenderID for channel sms_otp_sid or sms_notp_sid.'
          type: string
        provider:
          title: 'provider'
          description: 'Provider is base price to sending Notification: provider1, provider2'
          type: string
          default: 'provider2'
        otp:
          title: 'otp'
          description: 'SMS Type OTP or NON OTP: 0, 1'
          type: boolean
          default: 0
      type: object
      xml:
        name: BulkSms
    SendSms:
      title: 'Send SMS model'
      description: 'Send SMS model'
      required:
        - type
        - to
        - from
        - text
        - servid
      properties:
        type:
          title: 'Type'
          description: 'Character type for text: 0 - ASCII 5 - Unicode'
          type: integer
          format: int64
          example: 0
        servid:
          title: 'ServId'
          description: 'ServID'
          type: string
        to:
          title: 'To'
          description: 'The recipient’s mobile number must have the country code (without the “+” sign).'
          type: string
          format: msisdn
          example: "6281339668556"
        from:
          title: 'from'
          description: 'Sender’s name, Sender’s ID or Sender’s number'
          type: string
        title:
          title: 'Title'
          description: 'Broadcast Title'
          type: string
          example: "First Broadcast"
        text:
          title: 'Text'
          description: 'Message Content'
          type: string
          example: "Hello World!"
        otp:
          title: 'OTP'
          description: 'Is SMS Type OTP'
          type: boolean
          example: "true / false / 1 / 0"
      type: object
      xml:
        name: SingleSms
    Chat:
      title: 'Chat model'
      description: 'Chat model'
      required:
        - text
        - phone
      properties:
        phone:
          title: 'Phone'
          description: 'Phone User from'
          type: string
        reply:
          title: 'Reply'
          description: 'User Message Reply'
          type: string
        date:
          title: 'Date'
          description: 'Broadcast date'
          type: string
          format: date-time
      type: object
      xml:
        name: Chat
    InvalidInputChat:
      title: 'Invalid Chat'
      description: 'Chat model'
      required:
        - text
        - phone
      properties:
        message:
          title: 'Phone'
          description: 'Phone User from'
          type: string
        errors:
          title: 'Errors'
          description: 'Errors'
          type: array
          items:
            type: string
      type: object
      xml:
        name: InvalidInputChat
  requestBodies:
    Pet:
      description: 'Pet object that needs to be added to the store'
      required: true
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: 'List of user object'
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
    SmsArray:
    OneWayArray:
      description: 'List of sms object'
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/OneWayRequest'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  -
    name: chat
    description: 'API for Chat'
  -
    name: sms
    description: 'API for SMS'
  -
    name: one way
    description: 'API for 1 Way Channel Sending'
  -
    name: two way
    description: 'API for 2 Way Channel Sending'
